spring.profiles.active=default
spring.application.name=site
server.port=8080
spring.data.mongodb.database=test

spring.data.mongodb.uri=mongodb+srv://helloimdadu_db_user:5AGbeJ8TsedXXtIt@cluster0.emiuxbo.mongodb.net/?appName=Cluster0
# ---- Jackson ----
spring.jackson.default-property-inclusion=non_null

# ---- Logging ----
logging.level.com.cseplanner.journey=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
debug=true