spring.profiles.active=default
spring.application.name=site
server.port=${PORT:8080}
spring.data.mongodb.database=cse_journey_planner

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://helloimdadu_db_user:5AGbeJ8TsedXXtIt@cluster0.emiuxbo.mongodb.net/?appName=Cluster0}

# ---- Jackson ----
spring.jackson.default-property-inclusion=non_null

# ---- Logging ----
logging.level.com.example.cseplanner=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
